config/modules.yml
config/services.yml
includes/modules_helper.php
modules/announcements.php
modules/calendar.php
modules/news.php
modules/poll.php
modules/stylechanger.php
tests/mock/controller_helper.php
tests/unit/acp/move_module_test.php
tests/unit/functions/fetch_news_test.php
tests/unit/includes/modules_helper_test.php
tests/unit/modules/calendar_test.php
tests/unit/portal/fetch_posts_test.php

[ticket/436] Create routes using controller helper instead of directly creating app.php links

---

controller/main.php
styles/prosilver/template/portal/assets/portal.js

[ticket/426] Correctly align left and right columns if one is disabled

---

modules/statistics.php
portal/fetch_posts.php

[ticket/432] Improve worst rated functions and methods

---

portal/fetch_posts.php

[ticket/432] Further split get_posts() apart

---

language/es/info_acp_portal.php
language/es/modules/portal_announcements_module.php
language/es/modules/portal_attachments_module.php
language/es/modules/portal_birthday_list_module.php
language/es/modules/portal_calendar_module.php
language/es/modules/portal_clock_module.php
language/es/modules/portal_custom_module.php
language/es/modules/portal_donation_module.php
language/es/modules/portal_forumlist_module.php
language/es/modules/portal_friends_module.php
language/es/modules/portal_latest_bots_module.php
language/es/modules/portal_latest_members_module.php
language/es/modules/portal_leaders_module.php
language/es/modules/portal_link_us_module.php
language/es/modules/portal_links_module.php
language/es/modules/portal_main_menu_module.php
language/es/modules/portal_news_module.php
language/es/modules/portal_poll_module.php
language/es/modules/portal_random_member_module.php
language/es/modules/portal_recent_module.php
language/es/modules/portal_search_module.php
language/es/modules/portal_statistics_module.php
language/es/modules/portal_stylechanger_module.php
language/es/modules/portal_topposters_module.php
language/es/modules/portal_user_menu_module.php
language/es/modules/portal_welcome_module.php
language/es/modules/portal_whois_online_module.php
language/es/portal.php
language/es/portal_acp.php

Spanish translation, fixed errors whitespaces.

Spanish translation

---

README.md

[ticket/445] Add code quality and coverage badges to README

---

styles/prosilver/template/portal/modules/news_compact_center.html

[ticket/435] Correctly check if replies and views column is enabled in news

---

modules/announcements.php
modules/news.php
styles/prosilver/template/portal/modules/announcements_center_compact.html
styles/prosilver/template/portal/modules/news_compact_center.html
styles/prosilver/theme/portal_responsive.css

The repsonsiveness of those two blocks has also been improved.
Fixes #418

[ticket/418] Correctly assign paginatino in compact news and announcements

---

language/fr/info_acp_portal.php
language/fr/modules/portal_announcements_module.php
language/fr/modules/portal_attachments_module.php
language/fr/modules/portal_birthday_list_module.php
language/fr/modules/portal_calendar_module.php
language/fr/modules/portal_clock_module.php
language/fr/modules/portal_custom_module.php
language/fr/modules/portal_donation_module.php
language/fr/modules/portal_forumlist_module.php
language/fr/modules/portal_friends_module.php
language/fr/modules/portal_latest_bots_module.php
language/fr/modules/portal_latest_members_module.php
language/fr/modules/portal_leaders_module.php
language/fr/modules/portal_link_us_module.php
language/fr/modules/portal_links_module.php
language/fr/modules/portal_main_menu_module.php
language/fr/modules/portal_news_module.php
language/fr/modules/portal_poll_module.php
language/fr/modules/portal_random_member_module.php
language/fr/modules/portal_recent_module.php
language/fr/modules/portal_search_module.php
language/fr/modules/portal_statistics_module.php
language/fr/modules/portal_stylechanger_module.php
language/fr/modules/portal_topposters_module.php
language/fr/modules/portal_user_menu_module.php
language/fr/modules/portal_welcome_module.php
language/fr/modules/portal_whois_online_module.php
language/fr/portal.php
language/fr/portal_acp.php

- FRENCH translation for info_acp_portal.php file
- FRENCH translation for portal.php
- FRENCH translation for portal_acp.php
- FRENCH translation for /modules/portal_announcements_module.php
- FRENCH translation for /modules/portal_attachments_module.php
- FRENCH translation for /modules/portal_birthday_list_module.php
- FRENCH translation for /modules/portal_calendar_module.php
- FRENCH translation for /modules/portal_clock_module.php
- FRENCH translation for /modules/portal_custom_module.php
- FRENCH translation for /modules/portal_donation_module.php
- FRENCH translation for /modules/portal_forumlist_module.php
- FRENCH translation for /modules/portal_friends_module.php
- FRENCH translation for /modules/portal_latest_bots_module.php
- FRENCH translation for …

FRENCH translation for Board3 Portal extension

---

modules/leaders.php
styles/prosilver/template/portal/modules/leaders_side.html
styles/subsilver2/template/portal/modules/leaders_side.html

[ticket/452] Correctly show groups in leaders module

---

composer.json
migrations/v210_rc2.php
styles/prosilver/template/portal/modules/clock_side.html
styles/prosilver/template/portal/portal_body.html
styles/prosilver/theme/portal.css
styles/subsilver2/template/portal/modules/clock_side.html
styles/subsilver2/template/portal/portal_body.html

[ticket/449] Prepare package for 2.1.0-RC2 release

---

tests/unit/functions/version_check_test.php

[ticket/461] Fix tests for current version

---

language/fr/modules/portal_latest_bots_module.php
language/fr/modules/portal_random_member_module.php
language/fr/modules/portal_topposters_module.php

Update for FRENCH translation for portal_random_member_module.php file
Update for FRENCH translation for portal_latest_bots_module.php file
Update for FRENCH translation for portal_topposters_module.php file

Update for FRENCH translation for Board3 Portal extension

---

config/routing.yml
tests/functional/portal_no_error_test.php

[ticket/465] Use path instead of pattern in routing.yml

---

modules/announcements.php
modules/news.php
portal/fetch_posts.php

Also, text will no longer be shortened if the modules is using the compact
style.
Fixes #471

[ticket/471] Do not shorten text if limit is at 0

---

modules/news.php

[ticket/473] Correctly create news on read all page

---

modules/announcements.php

[ticket/475] Show "No announcements" if no announcements present

---

.travis.yml

[ticket/483] Use phpBB's 3.1.x branch for travis builds

---

modules/search.php

[ticket/481] Remove unneeded assignment of S_SEARCH_ACTION in search

---

styles/prosilver/theme/portal.css
styles/prosilver/theme/portal_responsive.css

[ticket/482] Get rid of conflicts between portal and phpBB CSS

---

acp/portal_module.php

[ticket/464] Use phpbb_admin_path for links to acp pages

---

includes/version_check.php
tests/unit/functions/version_check_test.php

[ticket/477] Expect version_helper to throw RuntimeException

---

acp/portal_module.php
tests/unit/acp/move_module_test.php

[ticket/492] Use B3P controller helper for loading module language

---

acp/portal_module.php
adm/style/portal/acp_portal_modules.html
controller/helper.php

[ticket/495] Correctly load template files for modules

---

acp/portal_module.php
includes/functions.php
modules/announcements.php
modules/attachments.php
modules/birthday_list.php
modules/latest_bots.php
modules/latest_members.php
modules/leaders.php
modules/news.php
modules/recent.php
modules/stylechanger.php
modules/topposters.php
modules/user_menu.php
portal/fetch_posts.php
portal/modules/manager.php
tests/unit/acp/move_module_test.php
tests/unit/functions/fetch_news_test.php
tests/unit/portal/fetch_posts_test.php
tests/unit/portal/modules_manager_confirm_box_test.php
tests/unit/portal/modules_manager_test.php

[ticket/494] Improve caching and query performance of portal

---

includes/functions.php
modules/calendar.php
styles/prosilver/template/portal/modules/main_menu_side.html
styles/prosilver/template/portal/modules/stylechanger_side.html
styles/prosilver/template/portal/portal_body.html
styles/subsilver2/template/portal/modules/main_menu_side.html
styles/subsilver2/template/portal/modules/stylechanger_side.html
styles/subsilver2/template/portal/portal_body.html

[ticket/498] Add nofollow for calendar and add roles for elements

---

styles/prosilver/theme/portal.css

[ticket/502] Remove inner rounded corners from center modules

---

config/modules.yml
modules/whois_online.php

[ticket/504] Order who is online based on phpBB ACP setting

---

controller/main.php
tests/mock/template.php
tests/unit/controller/main_test.php

[ticket/508] Only execute portal once when accessed via domain only

---

styles/prosilver/theme/portal.css

[ticket/511] Do not show <hr> at bottom of prosilver main menu

---

.travis.yml
modules/calendar.php
modules/links.php
modules/main_menu.php

[ticket/514] Add PHP7 to travis build matrix

---

modules/leaders.php

[ticket/510] Order groups by group_legend setting in leaders module

---

styles/prosilver/theme/portal_all_responsive.css

[ticket/522] Hide portal on all pages on low resolutions

---

modules/calendar.php

[ticket/521] Display correct day of week in calendar module

---

tests/unit/event/config/routing.yml

[ticket/525] Use path instead of pattern for routes in tests

---

language/fr/modules/portal_calendar_module.php

Update of FRENCH translation for portal_calendar_module.php file

Update of FRENCH translation for Board3 Portal extension

---

config/services.yml
portal/modules/manager.php
tests/unit/acp/move_module_test.php
tests/unit/portal/modules_manager_confirm_box_test.php
tests/unit/portal/modules_manager_test.php

[ticket/528] Correctly load module language for 3rd party modules

---

.travis.yml

[ticket/532] Update build excludes in travis.yml

---

README.md
composer.lock

[ticket/535] Update trimmessage tool

---

event/listener.php

[ticket/539] Do not show portal on all pages if board is disabled

---

migrations/v210_beta1.php
modules/attachments.php

[ticket/542] Add missing calls to sql_freeresult()

---

config/services.yml
controller/helper.php
tests/unit/acp/move_module_test.php
tests/unit/controller/helper_test.php
tests/unit/controller/main_test.php
tests/unit/event/listener_test.php
tests/unit/functions/fetch_news_test.php
tests/unit/functions/functions_test.php
tests/unit/functions/get_user_groups_test.php
tests/unit/functions/version_check_test.php
tests/unit/portal/fetch_posts_test.php
tests/unit/portal/modules_manager_confirm_box_test.php
tests/unit/portal/modules_manager_test.php

[ticket/546] Use phpbb\language\language for module language files

---

composer.json

[ticket/541] Update versions in composer.json

---

includes/functions.php
modules/announcements.php
modules/news.php

[ticket/553] Fix code sniffer complaints

---

composer.json
migrations/v210.php

[ticket/541] Update for final release of Board3 Portal

---

config/modules.yml
includes/modules_helper.php
language/de/modules/portal_donation_module.php
language/en/modules/portal_donation_module.php
migrations/v210.php
modules/donation.php
styles/prosilver/template/portal/modules/donation_center.html
styles/prosilver/template/portal/modules/donation_side.html
styles/subsilver2/template/portal/modules/donation_center.html
styles/subsilver2/template/portal/modules/donation_side.html
tests/unit/acp/move_module_test.php
tests/unit/includes/modules_helper_test.php
tests/unit/portal/modules_manager_confirm_box_test.php
tests/unit/portal/modules_manager_test.php

[ticket/555] Allow setting default currency in ACP

---

acp/portal_module.php
includes/functions.php
includes/modules_helper.php
migrations/v210_beta1.php
modules/announcements.php
modules/attachments.php
modules/latest_members.php
modules/leaders.php
modules/main_menu.php
modules/news.php
modules/poll.php
modules/recent.php
modules/stylechanger.php
modules/welcome.php
tests/unit/acp/move_module_test.php
tests/unit/portal/modules_manager_test.php

[ticket/558] Fix coding guidelines infractions

---

tests/unit/event/listener_test.php

[ticket/560] Properly instantiate router class in tests

---

acp/portal_info.php

[ticket/550] Use extension ACL variable in portal_info

---

includes/modules_helper.php
modules/attachments.php
tests/unit/includes/modules_helper_test.php

[ticket/565] Properly create select box for multiple options

---

event/listener.php

[ticket/569] Do not display portal on login page if board is disabled

---

migrations/v210.php
modules/calendar.php
modules/links.php
modules/main_menu.php

[ticket/572] Use json_decode/encode instead of serializing data

---

styles/prosilver/theme/portal.css

[ticket/575] Remove border-radius from top and bottom modules

---

adm/style/portal/ajax.js
styles/prosilver/template/portal/assets/portal.js
styles/prosilver/template/portal/portal_body.html

[ticket/578] Correctly assign classes to elements upon deleting/moving modules

---

README.md

[ticket/585] Use up-to-date images in README.md

---

modules/welcome.php
portal/fetch_posts.php

[ticket/588] Fix code sniffer issues in portal files [ci skip]

---

build.xml

[ticket/584] Make sure phpunit is available during build

---

build.xml

[ticket/584] Check for file instead of directory

---

build.xml

[ticket/592] Run phploc on jenkins build

---

build.xml

[ticket/592] Correctly check if already setup inside phpBB

---

build.xml

[ticket/592] Do not run phploc on complete git repository

---

build.xml

[ticket/592] Use proper relative path for phploc

---

styles/prosilver/template/portal/modules/clock_side.html
styles/subsilver2/template/portal/modules/clock_side.html

[ticket/583] Correctly show clock in legacy browsers

---

composer.lock

[ticket/597] Update composer.lock [ci skip]

---

build.xml

[ticket/601] Clone phpBB's master branch for master branch

---

build.xml

[ticket/603] Correctly exclude files from phploc report

---

build.xml

[ticket/605] Recursively chmod cache directory

---

build.xml

[ticket/605] Revert changes to chmod and change copy path [ci skip]

---

build.xml

[ticket/605] Fix incorrect path to config [ci skip]

---

styles/prosilver/theme/portal.css
styles/prosilver/theme/portal_responsive.css

[ticket/582] Improve responsiveness for prosilver SE

---

styles/prosilver/theme/portal.css

[ticket/582] Increase space for last post info [ci skip]

---

tests/functional/portal_visit_registered_test.php

[ticket/614] Select correct role ID for hidden forum

---

composer.json
composer.lock

[ticket/616] Update composer.json and composer.lock

---

controller/helper.php

[ticket/552] Correctly create path to module images

---

styles/prosilver/theme/portal.css

[ticket/619] Fix wrong overflow in compact center blocks

---

migrations/v210.php

[ticket/550] Update module_auth upon update to 2.1.0

---

styles/prosilver/theme/portal.css
styles/prosilver/theme/portal_all.css

[ticket/622] Return css settings to initial prosilver values in portal_all

---

controller/main.php
tests/unit/controller/main_test.php

[ticket/624] Display modules on all pages if column disabled in portal

---

styles/prosilver/theme/portal_all_responsive.css

[ticket/626] Correctly resize portal on all pages again

---

build.xml

[ticket/628] Name portal builds based on git commit ID [ci skip]

---

build.xml

[ticket/628] Correctly pass version.override [ci skip]

---

build.xml

[ticket/628] Properly parse build number

---

build.xml

[ticket/632] Use different test_config for 2.2.x builds [ci skip]

---

includes/functions.php
modules/calendar.php
tests/mock/check_form_key.php
tests/unit/event/listener_test.php
tests/unit/modules/calendar_test.php
tests/unit/modules/clock_test.php
tests/unit/modules/fixtures/configs.xml
tests/unit/modules/search_test.php
tests/unit/modules/welcome_test.php

[ticket/634] Increase test coverage

---

styles/prosilver/template/portal/assets/portal.js
styles/prosilver/theme/portal_all_responsive.css

[ticket/639] Fix slightly incorrect alignment in portal all view

---

styles/prosilver/template/event/overall_footer_page_body_after.html
styles/prosilver/template/event/overall_header_page_body_before.html
styles/prosilver/template/portal/_block_config.html
styles/prosilver/template/portal/assets/portal.js
styles/prosilver/template/portal/portal_body.html
styles/prosilver/theme/portal_all.css
styles/prosilver/theme/portal_all_responsive.css
styles/prosilver/theme/portal_responsive.css

[ticket/641] Correctly align portal columns with css

---

composer.json
modules/announcements.php
modules/birthday_list.php
modules/news.php
portal/fetch_posts.php

[ticket/644] Reduce caching time on portal page

---

styles/prosilver/template/portal/modules/donation_center.html
styles/prosilver/template/portal/modules/donation_side.html
styles/subsilver2/template/portal/modules/donation_center.html
styles/subsilver2/template/portal/modules/donation_side.html

[ticket/648] Add missing brackets to donations HTML files

---

tests/unit/acp/move_module_test.php
tests/unit/controller/helper_test.php
tests/unit/controller/main_test.php
tests/unit/event/listener_test.php
tests/unit/modules/calendar_test.php
tests/unit/modules/welcome_test.php
tests/unit/portal/modules_manager_confirm_box_test.php
tests/unit/portal/modules_manager_test.php

[ticket/652] Fix test failures caused by latest changes to phpBB's master

---

language/fr/permissions_portal.php

Hi @marc1706,
could you merge this, please ?
Note: there was a bad encoding in this file (ANSI instead of UTF-8 (without BOM), maybe other equivalent language files have the same issue.

Minor update of FRENCH language for Board3 Portal extension

---

.travis.yml
tests/unit/event/listener_test.php

[ticket/660] Update tests for recent changes in 3.2.x

---

.travis.yml

[ticket/661] Remove PHP7 from allowed failures

---

modules/recent.php
portal/fetch_posts.php

[ticket/666] Reduce caching time of post related queries

---

tests/functional/portal_announcement_test.php
tests/functional/portal_birthday_list_test.php
tests/functional/portal_no_error_test.php

[ticket/669] Purge cache if necessary in functional tests

---

styles/prosilver/theme/portal_all_responsive.css

[ticket/656] Reduce margin of topiclist in responsive portal all

---

tests/unit/modules/welcome_test.php

[ticket/674] Define textformatter factory correctly

---

build.xml

[ticket/676] Set cache permissions recursively

---

styles/prosilver/template/portal/modules/poll_center.html
styles/prosilver/template/portal/modules/poll_side.html

[ticket/679] Add horizontal line to poll module

---

language/de/modules/portal_announcements_module.php

[ticket/678] Fix typo in German language file

---

composer.lock

[ticket/696] Update text shortener to latest version

---

tests/testframework/ui_test_case.php
tests/ui/portal_visit_ui_test.php

Depends on linked phpBB PR and probably will require some changes to the travis script
Fixes #686

[ticket/686] Add possibility to use UI tests

---

.travis.yml
tests/unit/includes/modules_helper_test.php

[ticket/704] Update .travis.yml for travis changes

---

build.xml

[ticket/704] Fix call to phploc.phar

---

build.xml

[ticket/704] Checkout 3.1.x in build.xml

---

build.xml

[ticket/718] Use 3.3.x in phing builds
